CREATE TABLE CUSTOMER
(
ID INT,
NAME VARCHAR(10),
AGE INT,
ADDRESS VARCHAR(10),
SALARY INT

)
DROP TABLE CUSTOMER
SELECT * FROM CUSTOMER


INSERT INTO CUSTOMER (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO CUSTOMER (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO CUSTOMER (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO CUSTOMER (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMER (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO CUSTOMER (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );

UPDATE CUSTOMER
SET SALARY=3000
WHERE ID=2;
ALTER TABLE CUSTOMER ADD LOCID INT
SELECT * FROM CUSTOMER
CREATE TABLE LOCATION
(
LOCID INT,
LOCNAME VARCHAR(10)
)
SELECT * FROM LOCATION
INSERT INTO LOCATION VALUES(301,'HYDERABAD')
INSERT INTO LOCATION VALUES(302,'BANGALORE')

UPDATE EMPLOYEE
SET LOCID=301
WHERE ID=1